spring:
    sms:
        enabled: true
        current-provider: ALIYUN
        #运行模式 debug:调试模式（返回9999）,release:发布模式，将实际发送短信
        running-mode: release
        #阿里云短信
        aliyun:
            #区域id，参考 https://help.aliyun.com/document_detail/40654.html?spm=a2c6h.13066369.0.0.c85c7eecnh6fH6
            region-id: cn-chengdu
            #产品名称:云通信短信API产品,开发者无需替换
            name: Dysmsapi
            #产品域名,开发者无需替换
            domain: dysmsapi.aliyuncs.com
            #产品keyid
            key-id: XXXXX
            #产品keysecret
            key-secret: XXXXX
            #短信签名
            sign-name: 百灵鸟
            #读取超时时间
            read-timeout: 10000
            #连接超时时间
            connect-timeout: 10000
            #短信模板编号
            templates:
                #登陆验证码
                verification-code: SMS_26700XXXX